#!/bin/bash
PATH=/usr/local/bin:/usr/bin:/bin

abspath="$(cd "${0%/*}" 2>/dev/null; echo "$PWD"/"${0##*/}")"
log_dir=`dirname $abspath`
root_dir=`dirname $log_dir`
app_name=`basename $root_dir`

exec 2>&1
exec cat > $log_dir/$app_name.log
